### ISSUE TITLE
Warnings "point arrived late" when using -delay option

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-twitter-adapter#10]
When I run the twitter demo program, outriggerd console output has lots of warnings like this:
```
[2016-01-08 17:36:56.734] [WARN] juttle-procs read twitter - point arrived late 2016-01-09T01:36:57.000Z 2016-01-09T01:36:50.595Z
```

Even if I set delay to 10 seconds, I see my resulting chart progressing in 10-second increments, but there are still warnings on the console, seemingly the same volume of them. I thought we'd stop warning because points would be within the tolerable delay.

My juttle read is:
```
read twitter -stream true -delay :10s:
```

By the way README says `delay for the given latency (in ms)` but that can't be right, I only saw delay take effect properly when passing in a juttle moment like `:10s:`, the numeric value like 2000 or 2 resulted in my program sitting there with no output. Doc update needed?

**Comment by demmer** [comment]
Closing an old issue -- the `-lag` option should cover this case.
